apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: syncrets-sa
  namespace: cert-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: syncrets-role
  namespace: cert-manager
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: syncrets-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: syncrets-role
subjects:
- kind: ServiceAccount
  name: syncrets-sa
  namespace: cert-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: syncrets
  name: syncrets
  namespace: cert-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syncrets
  strategy: {}
  template:
    metadata:
      labels:
        app: syncrets
    spec:
      serviceAccountName: syncrets-sa
      containers:
      - image: localhost/syncrets:4.0
        name: syncrets
        imagePullPolicy: IfNotPresent
